"""
Services module for POE Knowledge Assistant.
Contains business logic and external service integrations.
"""

from src.services.chroma_db import (
    ChromaDBManager,
    ChromaDBError,
    get_chroma_manager,
    check_chromadb_health,
)
from src.services.embeddings import (
    LocalEmbeddings,
    OpenAIEmbeddings,
    EmbeddingError,
    get_local_embeddings,
    check_embeddings_health,
    create_embeddings,
)
from src.services.vector_store import (
    VectorStore,
    VectorStoreError,
    get_embeddings,
    get_vector_store,
    check_vector_store_health,
)
from src.services.rag_chain import (
    RAGChain,
    RAGChainError,
    Citation,
    RetrievalResult,
    get_rag_chain,
    check_rag_chain_health,
)
from src.services.llm_provider import (
    OpenAILLM,
    AnthropicLLM,
    OllamaLLM,
    LMStudioLLM,
    LLMProviderError,
    create_llm,
    get_llm,
    check_llm_health,
)
from src.services.streaming import (
    StreamingError,
    generate_streaming_response,
    check_streaming_health,
)
from src.services.scraper import (
    ScraperError,
    ScraperConnectionError,
    ScraperHTTPError,
    ScraperRateLimitError,
    ScraperParsingError,
    ScraperTimeoutError,
    HTTPClient,
    DEFAULT_BASE_URL,
    BaseScraper,
    ScrapeResult,
    ScrapeBatchResult,
    SimpleScraper,
    check_scraper_health,
    SELECTORS,
    safe_get_text,
    safe_get_attr,
    find_first,
    find_all,
    extract_page_title,
    extract_item_name,
    extract_stats,
    extract_flavor_text,
    extract_requirements,
    extract_image_url,
    extract_links,
    extract_table_data,
)
from src.services.indexer import (
    ChromaDBIndexer,
    IndexerError,
    get_indexer,
    index_items,
    check_indexer_health,
)

__all__ = [
    "ChromaDBManager",
    "ChromaDBError",
    "get_chroma_manager",
    "check_chromadb_health",
    "LocalEmbeddings",
    "OpenAIEmbeddings",
    "EmbeddingError",
    "get_local_embeddings",
    "check_embeddings_health",
    "create_embeddings",
    "VectorStore",
    "VectorStoreError",
    "get_embeddings",
    "get_vector_store",
    "check_vector_store_health",
    "RAGChain",
    "RAGChainError",
    "Citation",
    "RetrievalResult",
    "get_rag_chain",
    "check_rag_chain_health",
    "OpenAILLM",
    "AnthropicLLM",
    "OllamaLLM",
    "LMStudioLLM",
    "LLMProviderError",
    "create_llm",
    "get_llm",
    "check_llm_health",
    "StreamingError",
    "generate_streaming_response",
    "check_streaming_health",
    # Scraper
    "ScraperError",
    "ScraperConnectionError",
    "ScraperHTTPError",
    "ScraperRateLimitError",
    "ScraperParsingError",
    "ScraperTimeoutError",
    "HTTPClient",
    "DEFAULT_BASE_URL",
    "BaseScraper",
    "ScrapeResult",
    "ScrapeBatchResult",
    "SimpleScraper",
    "check_scraper_health",
    # Scraper DOM parsers
    "SELECTORS",
    "safe_get_text",
    "safe_get_attr",
    "find_first",
    "find_all",
    "extract_page_title",
    "extract_item_name",
    "extract_stats",
    "extract_flavor_text",
    "extract_requirements",
    "extract_image_url",
    "extract_links",
    "extract_table_data",
    # Indexer
    "ChromaDBIndexer",
    "IndexerError",
    "get_indexer",
    "index_items",
    "check_indexer_health",
]
